DROP TABLE IF EXISTS SmsRequest;
DROP TABLE IF EXISTS Operator;
DROP TABLE IF EXISTS phoneCodeMapping;

CREATE TABLE SmsRequest (smsRequestId BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1 ), creationDate TIMESTAMP NOT NULL, incomingId VARCHAR(255) NOT NULL, messageText VARCHAR(255) NOT NULL, operatorMessageId VARCHAR(255), phoneNumber VARCHAR(255) NOT NULL, status VARCHAR(255), systemName VARCHAR(255) NOT NULL, updateDate TIMESTAMP, operatorId BIGINT, PRIMARY KEY (smsRequestId));
--CREATE TABLE "SmsRequest"  (
--  id BIGINT GENERATED BY DEFAULT AS IDENTITY,
--  "incomingId" varchar(32) NOT NULL,
--  "systemName" varchar(45) NOT NULL,
--  "phoneNumber" varchar(10) NOT NULL,
--  "messageText" varchar(200) NOT NULL,
--  "creationDate" timestamp NOT NULL,
--  "updateDate" timestamp,
--  "status" varchar(64),
--  operatorId INT,
--  "operatorMessageId" varchar(64));

CREATE TABLE Operator (operatorId BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1 ), name VARCHAR(255) NOT NULL, PRIMARY KEY (operatorId));
--create table Operator (
--  id INT GENERATED BY DEFAULT AS IDENTITY,
--  name varchar(45) not null
--);

CREATE TABLE phoneCodeMapping (operatorId BIGINT NOT NULL, phoneCodes VARCHAR(255));
--create table phoneCodeMapping (
--  id int GENERATED BY DEFAULT AS IDENTITY,
--  operatorId int not null,
--  phoneCodes varchar(3)
--);
