CREATE TABLE "smsRequest" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY,
  "incomingId" varchar(32) NOT NULL,
  "systemName" varchar(45) NOT NULL,
  "phoneNumber" varchar(10) NOT NULL,
  "messageText" varchar(200) NOT NULL,
  "creationDate" timestamp NOT NULL,
  "updateDate" timestamp,
  "status" varchar(64),
  "operatorId" INT,
  "operatorMessageId" varchar(64));

create table "operator" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY,
  "name" varchar(45) not null
);

create table "phoneCodeMapping" (
  "id" int GENERATED BY DEFAULT AS IDENTITY,
  "operatorId" int not null,
  "phoneCodes" varchar(3)
);

