CREATE TABLE "smsRequest" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY,
  "incomingId" varchar(32) NOT NULL,
  "sytemName" varchar(45) NOT NULL,
  "phoneNumber" varchar(10) NOT NULL,
  "messageText" varchar(200) NOT NULL,
  "creationDate" timestamp NOT NULL,
  "updateDate" timestamp,
  "status" varchar(64),
  "operator" varchar(127),
  "operatorMessageId" varchar(64));

